// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByMjVdNpUyCHjw6ZSeW_Azy-TYOX8MVU4',
    appId: '1:567409166422:web:c2703bb7cb2029aa3893f7',
    messagingSenderId: '567409166422',
    projectId: 'cmsc23-jcgarin',
    authDomain: 'cmsc23-jcgarin.firebaseapp.com',
    storageBucket: 'cmsc23-jcgarin.appspot.com',
    measurementId: 'G-TNNTY88SG3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8iNfUkDvKqpfDZvZcVCtE5LGzw4Pa16A',
    appId: '1:567409166422:android:6c71dd273989b8a53893f7',
    messagingSenderId: '567409166422',
    projectId: 'cmsc23-jcgarin',
    storageBucket: 'cmsc23-jcgarin.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqvGsDe0CeE2xMK4jeE9cIuMzcqVtaZuE',
    appId: '1:567409166422:ios:c4c6c2ae86072c0d3893f7',
    messagingSenderId: '567409166422',
    projectId: 'cmsc23-jcgarin',
    storageBucket: 'cmsc23-jcgarin.appspot.com',
    iosClientId: '567409166422-8v89sdfhajbo2nh0qvh6ecu6vnti656q.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqvGsDe0CeE2xMK4jeE9cIuMzcqVtaZuE',
    appId: '1:567409166422:ios:c4c6c2ae86072c0d3893f7',
    messagingSenderId: '567409166422',
    projectId: 'cmsc23-jcgarin',
    storageBucket: 'cmsc23-jcgarin.appspot.com',
    iosClientId: '567409166422-8v89sdfhajbo2nh0qvh6ecu6vnti656q.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
